slug: wsc
visit: wsc_vst
charts:
- chart: sex
  title: Gender
- chart: race
  title: Race
webservers:
  - name: production
    url: https://sleepdata.org
  - name: staging
    url: https://staging.partners.org/sleepdata.org
